version: "2.2"
services:
  jobmanager:
    image: flink:1.13.6-scala_2.11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager    
        jobmanager.memory.process.size: 1024m    

  taskmanager:
    image: flink:1.13.6-scala_2.11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2   
        taskmanager.memory.process.size: 2048m
        state.backend.latency-track.keyed-state-enabled: true